In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd

In [30]:
master_df = pd.read_csv('/content/drive/MyDrive/master_dataset.csv')
master_df['store_names'] = master_df['store_names'].str.strip()
master_df.head()

,store_lats,store_lngs,store_sizes,store_products,store_categories,days_to_expiry,quantity_available,original_prices,discounted_prices,is_available,store_names,store_addresses
0,38.930205,-77.038273,medium,chicken drumstick,meat,1,103,0.42,0.252000,0,El Progreso Market,3158 MOUNT PLEASANT STREET NW
1,38.921987,-77.038442,medium,carrot,produce,5,156,0.63,0.540000,1,Harris Teeter,1631 KALORAMA ROAD NW
2,38.957977,-77.002144,medium,mustard,sauce/condiments,2,7,4.26,2.272000,0,Walmart Supercenter,310 RIGGS ROAD NE
3,38.944507,-77.063173,medium,ketchup,sauce/condiments,3,208,5.41,2.975500,1,Giant,4303 CONNECTICUT AVENUE NW
4,38.876224,-77.000097,medium,onion,produce,5,172,0.47,0.402857,1,Harris Teeter,401 M St SE

In [8]:
master_df.shape

(5000, 12)

In [31]:
sampled_stores = master_df[['store_names', 'store_addresses']].drop_duplicates().sample(3, random_state=42)
sampled_stores

       store_names             store_addresses
58          Target     1515 NEW YORK AVENUE NE
28         Safeway  5545 CONNECTICUT AVENUE NW
98  Streets Market         1255 22ND STREET NW

In [32]:
sampled_df = master_df[master_df['store_names'].isin(sampled_stores['store_names']) & master_df['store_addresses'].isin(sampled_stores['store_addresses'])]
sampled_df.head()

,store_lats,store_lngs,store_sizes,store_products,store_categories,days_to_expiry,quantity_available,original_prices,discounted_prices,is_available,store_names,store_addresses
28,38.964601,-77.074910,small,apple juice,beverages,98,29,2.32,1.791556,1,Safeway,5545 CONNECTICUT AVENUE NW
58,38.916268,-76.982013,medium,onion,produce,5,178,0.47,0.402857,1,Target,1515 NEW YORK AVENUE NE
98,38.906690,-77.048363,small,tuna,canned,65,53,13.40,7.893151,1,Streets Market,1255 22ND STREET NW
142,38.916268,-76.982013,medium,ranch dressing,sauce/condiments,1,185,10.75,5.554167,1,Target,1515 NEW YORK AVENUE NE
186,38.916268,-76.982013,medium,elbow macaroni,grain,113,225,1.09,0.887139,1,Target,1515 NEW YORK AVENUE NE

In [38]:
sampled_df.groupby('store_names').size()

store_names
Safeway           52
Streets Market    50
Target            60
dtype: int64

In [42]:
#sampled_df.to_csv('/content/drive/MyDrive/sampled_stores.csv', index=False)